spring:
  rabbitmq:
    host: "${RABBIT_HOST:localhost}"
    port: "${RABBIT_PORT:5672}"
    username: "${RABBIT_USERNAME:admin}"
    password: "${RABBIT_PASSWORD:admin}"
  r2dbc:
    url: "${DB_URL:r2dbc:pool:mysql://localhost:3306/bank_db}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:root}"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG
  application:
    name: customers-persons-ms
